"""Auto-generated dynamics for the 3-DOF RRR manipulator.

Generated by scripts/generate_dynamics.py on 2026-04-21 14:34:20.
Do not hand-edit; regenerate via `uv run python scripts/generate_dynamics.py`.
"""

import numpy as np


def compute_D(q, L, m, g, I):
    """Mass matrix D(q)."""
    q1, q2, q3 = q[0], q[1], q[2]
    t0 = L**2*m
    t1 = (1/4)*t0
    t2 = np.sin(q3)
    t3 = t2**2
    t4 = np.sin(q2)
    t5 = t3*t4**2 - t3
    t6 = (1/2)*I
    t7 = np.cos(q3)
    t8 = 2*t7
    t9 = -1/4*t2*(I*t8 + t0*t7 + 2*t0)*np.cos(q2)
    t10 = -1/4*t4*(4*I + t0*(t8 + 1))
    D = np.array([
        (3/2)*I + t1*(t5 + 4*t7 + 5) + t1 + t6*(t5 + 2),
        t9,
        t10,
        t9,
        I + t1*t3 + t3*t6,
        0,
        t10,
        0,
        I + t1
    ]).reshape(3, 3, order='F')
    return D


def compute_B(q, L, m, g, I):
    """Coriolis matrix B(q); multiplies [q1d*q2d, q1d*q3d, q2d*q3d]."""
    q1, q2, q3 = q[0], q[1], q[2]
    t0 = np.cos(q2)
    t1 = np.sin(q3)
    t2 = t1**2
    t3 = L**2*m
    t4 = np.cos(q3)
    t5 = t0**2*t4
    t6 = 2*I
    t7 = t4**2
    t8 = (1/2)*t0
    t9 = t8*(I + t2*t3 + t2*t6)
    B = np.array([
        t0*t2*(I + (1/2)*t3)*np.sin(q2),
        0,
        -t9,
        -1/2*t1*(t3*(t5 + 2) + t5*t6),
        t9,
        0,
        -t8*(I + 2*t3*t4 + t3*t7 + t6*t7),
        ((1/2)*I + (1/4)*t3)*np.sin(2*q3),
        0
    ]).reshape(3, 3, order='F')
    return B


def compute_C(q, L, m, g, I):
    """Centrifugal matrix C(q); multiplies [q1d^2, q2d^2, q3d^2]."""
    q1, q2, q3 = q[0], q[1], q[2]
    t0 = np.cos(q3)
    t1 = 2*I
    t2 = L**2*m
    t3 = np.sin(q2)
    t4 = np.sin(q3)
    t5 = (1/4)*t4
    t6 = np.cos(q2)
    t7 = t0*t6**2
    C = np.array([
        0,
        t3*t4**2*t6*(-1/2*I - 1/4*t2),
        t5*(t1*t7 + t2*(t7 + 2)),
        t3*t5*(t0*t1 + t0*t2 + 2*t2),
        0,
        (-1/4*I - 1/8*t2)*np.sin(2*q3),
        (1/2)*t2*t3*t4,
        0,
        0
    ]).reshape(3, 3, order='F')
    return C


def compute_G(q, L, m, g, I):
    """Gravity vector G(q)."""
    q1, q2, q3 = q[0], q[1], q[2]
    t0 = (1/2)*L*g*m
    G = np.array([
        0,
        -t0*np.sin(q2)*np.sin(q3),
        t0*np.cos(q2)*np.cos(q3)
    ])
    return G
