"""
Mass matrix (D matrix) computation for the 3-DOF RRR manipulator.

This file was AUTO-GENERATED by scripts/generate_dynamics.py
Generated on: 2025-12-10 21:28:30

DO NOT EDIT THIS FILE MANUALLY!
To regenerate, run: python scripts/generate_dynamics.py
"""

import numpy as np


def compute_D(q, L, m, g, I):
    """
    Compute the D matrix (Mass matrix) matrix/vector.
    
    This function was derived symbolically from first principles using
    Lagrangian mechanics and then optimized for computational efficiency.
    
    Parameters
    ----------
    q : array_like (3,)
        Joint angles [q1, q2, q3] in radians
    L : float
        Link length parameter
    m : float
        Link mass
    g : float
        Gravitational acceleration
    I : float
        Link inertia (perpendicular to link centerline)
        
    Returns
    -------
    D : ndarray
        D matrix (Mass matrix)
        
    Notes
    -----
    Derived from Lagrangian mechanics using the following steps:
    1. Forward kinematics → Transformation matrices
    2. Jacobians → Linear and angular velocity mappings
    3. Lagrangian → Kinetic and potential energy
    4. Euler-Lagrange equations → Equations of motion
    """
    q = np.asarray(q)
    q1, q2, q3 = q[0], q[1], q[2]
    
    # Precompute common subexpressions
    t0 = L**2*m
    t1 = (1/4)*t0
    t2 = np.sin(q3)
    t3 = t2**2
    t4 = np.sin(q2)
    t5 = t3*t4**2 - t3
    t6 = (1/2)*I
    t7 = np.cos(q3)
    t8 = 2*t7
    t9 = -1/4*t2*(I*t8 + t0*t7 + 2*t0)*np.cos(q2)
    t10 = -1/4*t4*(4*I + t0*(t8 + 1))
    
    # Construct D matrix using column-major (Fortran) order
    D = np.array([
        (3/2)*I + t1*(t5 + 4*t7 + 5) + t1 + t6*(t5 + 2),
        t9,
        t10,
        t9,
        I + t1*t3 + t3*t6,
        0,
        t10,
        0,
        I + t1
    ]).reshape(3, 3, order='F')
    
    return D
