"""
Centrifugal matrix (C matrix) computation for the 3-DOF RRR manipulator.

This file was AUTO-GENERATED by scripts/generate_dynamics.py
Generated on: 2025-12-10 21:28:30

DO NOT EDIT THIS FILE MANUALLY!
To regenerate, run: python scripts/generate_dynamics.py
"""

import numpy as np


def compute_C(q, L, m, g, I):
    """
    Compute the C matrix (Centrifugal matrix) matrix/vector.
    
    This function was derived symbolically from first principles using
    Lagrangian mechanics and then optimized for computational efficiency.
    
    Parameters
    ----------
    q : array_like (3,)
        Joint angles [q1, q2, q3] in radians
    L : float
        Link length parameter
    m : float
        Link mass
    g : float
        Gravitational acceleration
    I : float
        Link inertia (perpendicular to link centerline)
        
    
    The centrifugal matrix multiplies the vector of squared velocities:
    [q1_dot^2, q2_dot^2, q3_dot^2]^T
    
    Returns
n    -------
    C : ndarray
        C matrix (Centrifugal matrix)
        
    Notes
    -----
    Derived from Lagrangian mechanics using the following steps:
    1. Forward kinematics → Transformation matrices
    2. Jacobians → Linear and angular velocity mappings
    3. Lagrangian → Kinetic and potential energy
    4. Euler-Lagrange equations → Equations of motion
    """
    q = np.asarray(q)
    q1, q2, q3 = q[0], q[1], q[2]
    
    # Precompute common subexpressions
    t0 = np.cos(q3)
    t1 = 2*I
    t2 = L**2*m
    t3 = np.sin(q2)
    t4 = np.sin(q3)
    t5 = (1/4)*t4
    t6 = np.cos(q2)
    t7 = t0*t6**2
    
    # Construct C matrix using column-major (Fortran) order
    C = np.array([
        0,
        t3*t4**2*t6*(-1/2*I - 1/4*t2),
        t5*(t1*t7 + t2*(t7 + 2)),
        t3*t5*(t0*t1 + t0*t2 + 2*t2),
        0,
        (-1/4*I - 1/8*t2)*np.sin(2*q3),
        (1/2)*t2*t3*t4,
        0,
        0
    ]).reshape(3, 3, order='F')
    
    return C
