"""
Gravity vector (G vector) computation for the 3-DOF RRR manipulator.

This file was AUTO-GENERATED by scripts/generate_dynamics.py
Generated on: 2025-12-10 21:28:30

DO NOT EDIT THIS FILE MANUALLY!
To regenerate, run: python scripts/generate_dynamics.py
"""

import numpy as np


def compute_G(q, L, m, g, I):
    """
    Compute the G vector (Gravity vector) matrix/vector.
    
    This function was derived symbolically from first principles using
    Lagrangian mechanics and then optimized for computational efficiency.
    
    Parameters
    ----------
    q : array_like (3,)
        Joint angles [q1, q2, q3] in radians
    L : float
        Link length parameter
    m : float
        Link mass
    g : float
        Gravitational acceleration
    I : float
        Link inertia (perpendicular to link centerline)
        
    Returns
    -------
    G : ndarray
        G vector (Gravity vector)
        
    Notes
    -----
    Derived from Lagrangian mechanics using the following steps:
    1. Forward kinematics → Transformation matrices
    2. Jacobians → Linear and angular velocity mappings
    3. Lagrangian → Kinetic and potential energy
    4. Euler-Lagrange equations → Equations of motion
    """
    q = np.asarray(q)
    q1, q2, q3 = q[0], q[1], q[2]
    
    # Precompute common subexpressions
    t0 = (1/2)*L*g*m
    
    # Compute gravity vector components
    G = np.array([
        0,
        -t0*np.sin(q2)*np.sin(q3),
        t0*np.cos(q2)*np.cos(q3)
    ])
    
    return G
