#!/usr/bin/env python
"""Derive symbolic dynamics and emit src/pyrobo/dynamics/_generated.py.

Uses `sympy.cse` for common subexpression elimination and
`sympy.printing.numpy.NumPyPrinter` for code emission — no hand-rolled
string building. The symbolic derivation itself lives in
`symbolic_derivation.py` and is intentionally kept separate as the
pedagogical centerpiece.

Usage:
    uv run python scripts/generate_dynamics.py
"""

import sys
from datetime import datetime
from pathlib import Path

import sympy as sp
from sympy.printing.numpy import NumPyPrinter

sys.path.insert(0, str(Path(__file__).parent.parent))

from scripts.symbolic_derivation import derive_all_dynamics


_HEADER = '''"""Auto-generated dynamics for the 3-DOF RRR manipulator.

Generated by scripts/generate_dynamics.py on {timestamp}.
Do not hand-edit; regenerate via `uv run python scripts/generate_dynamics.py`.
"""

import numpy as np
'''


_FUNC_TEMPLATE = '''

def {name}(q, L, m, g, I):
    """{docstring}"""
    q1, q2, q3 = q[0], q[1], q[2]
{body}
    return {ret}
'''


def _pp(expr, printer):
    return printer.doprint(expr).replace("numpy.", "np.")


def _matrix_body(name, expr, printer):
    subexprs, (reduced,) = sp.cse(expr, symbols=sp.numbered_symbols("t"))
    lines = [f"    {var} = {_pp(sub, printer)}" for var, sub in subexprs]
    elements = [_pp(reduced[i, j], printer) for j in range(3) for i in range(3)]
    joined = ",\n        ".join(elements)
    lines.append(
        f"    {name} = np.array([\n        {joined}\n    ]).reshape(3, 3, order='F')"
    )
    return "\n".join(lines)


def _vector_body(name, expr, printer):
    subexprs, (reduced,) = sp.cse(expr, symbols=sp.numbered_symbols("t"))
    lines = [f"    {var} = {_pp(sub, printer)}" for var, sub in subexprs]
    elements = [_pp(reduced[i], printer) for i in range(3)]
    joined = ",\n        ".join(elements)
    lines.append(f"    {name} = np.array([\n        {joined}\n    ])")
    return "\n".join(lines)


def render_module(dynamics):
    """Return source for src/pyrobo/dynamics/_generated.py."""
    printer = NumPyPrinter()
    specs = [
        ("compute_D", "D", dynamics["D"], "Mass matrix D(q).", _matrix_body),
        (
            "compute_B",
            "B",
            dynamics["B"],
            "Coriolis matrix B(q); multiplies [q1d*q2d, q1d*q3d, q2d*q3d].",
            _matrix_body,
        ),
        (
            "compute_C",
            "C",
            dynamics["C"],
            "Centrifugal matrix C(q); multiplies [q1d^2, q2d^2, q3d^2].",
            _matrix_body,
        ),
        ("compute_G", "G", dynamics["G"], "Gravity vector G(q).", _vector_body),
    ]

    src = _HEADER.format(timestamp=datetime.now().strftime("%Y-%m-%d %H:%M:%S"))
    for fn_name, ret_name, expr, doc, body_fn in specs:
        src += _FUNC_TEMPLATE.format(
            name=fn_name,
            docstring=doc,
            body=body_fn(ret_name, expr, printer),
            ret=ret_name,
        )
    return src


def main():
    print("Deriving symbolic dynamics (30-90s)...")
    dynamics = derive_all_dynamics()

    print("\nRendering NumPy module...")
    src = render_module(dynamics)

    out_path = (
        Path(__file__).parent.parent / "src" / "pyrobo" / "dynamics" / "_generated.py"
    )
    out_path.write_text(src)
    print(f"  wrote {out_path.relative_to(Path(__file__).parent.parent)}")
    print("\nRun `uv run python tests/test_dynamics.py` to verify.")


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\nInterrupted.", file=sys.stderr)
        sys.exit(1)
